/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypackage;

import java.awt.Color;

/**
 *
 * @author abhig
 */
public class TTT extends javax.swing.JFrame {

    /**
     * Creates new form TTT
     */
public void check(){
String b1 = bt1.getText();
String b2 = bt2.getText();
String b3 = bt3.getText();
String b4 = bt4.getText();
String b5 = bt5.getText();
String b6 = bt6.getText();
String b7 = bt7.getText();
String b8 = bt8.getText();
String b9 = bt9.getText();
if(b1 == null ? b2 == null : b1.equals(b2)){if(b2 == null ? b3 == null : b2.equals(b3)){if("X".equals(b1)){jLabel2.setText("X is winner!");}else{jLabel2.setText("0 is winner!");}}}
if(b1 == null ? b4 == null : b1.equals(b4)){if(b4 == null ? b7 == null : b4.equals(b7)){if("X".equals(b1)){jLabel2.setText("X is winner!");}else{jLabel2.setText("0 is winner!");}}}
if(b1 == null ? b5 == null : b1.equals(b5)){if(b5 == null ? b9 == null : b5.equals(b9)){if("X".equals(b1)){jLabel2.setText("X is winner!");}else{jLabel2.setText("0 is winner!");}}}
if(b2 == null ? b5 == null : b2.equals(b5)){if(b5 == null ? b8 == null : b5.equals(b8)){if("X".equals(b2)){jLabel2.setText("X is winner!");}else{jLabel2.setText("0 is winner!");}}}
if(b3 == null ? b6 == null : b3.equals(b6)){if(b6 == null ? b9 == null : b6.equals(b9)){if("X".equals(b3)){jLabel2.setText("X is winner!");}else{jLabel2.setText("0 is winner!");}}}
if(b3 == null ? b5 == null : b3.equals(b5)){if(b5 == null ? b7 == null : b5.equals(b7)){if("X".equals(b3)){jLabel2.setText("X is winner!");}else{jLabel2.setText("0 is winner!");}}}
if(b4 == null ? b5 == null : b4.equals(b5)){if(b5 == null ? b6 == null : b5.equals(b6)){if("X".equals(b4)){jLabel2.setText("X is winner!");}else{jLabel2.setText("0 is winner!");}}}
if(b7 == null ? b8 == null : b7.equals(b8)){if(b8 == null ? b9 == null : b8.equals(b9)){if("X".equals(b7)){jLabel2.setText("X is winner!");}else{jLabel2.setText("0 is winner!");}}}

if(!"1".equals(b1)){if(!"2".equals(b2)){if(!"3".equals(b3)){if(!"4".equals(b4)){if(!"5".equals(b5)){if(!"6".equals(b6)){if(!"7".equals(b7)){if(!"8".equals(b8)){if(!"9".equals(b9)){jLabel2.setText("Game is Draw!");}}}}}}}}}
}

    public TTT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        board_panel = new javax.swing.JPanel();
        bt1 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ngbt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 204));
        jLabel1.setText("Welcome to Tic Toc Toe");

        board_panel.setBackground(new java.awt.Color(204, 102, 255));

        bt1.setBackground(new java.awt.Color(102, 102, 102));
        bt1.setFont(new java.awt.Font("ROG Fonts", 3, 36)); // NOI18N
        bt1.setForeground(new java.awt.Color(255, 0, 0));
        bt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt1MouseClicked(evt);
            }
        });

        bt4.setBackground(new java.awt.Color(102, 102, 102));
        bt4.setFont(new java.awt.Font("ROG Fonts", 3, 36)); // NOI18N
        bt4.setForeground(new java.awt.Color(255, 0, 0));
        bt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt4MouseClicked(evt);
            }
        });

        bt2.setBackground(new java.awt.Color(102, 102, 102));
        bt2.setFont(new java.awt.Font("ROG Fonts", 3, 36)); // NOI18N
        bt2.setForeground(new java.awt.Color(255, 0, 0));
        bt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt2MouseClicked(evt);
            }
        });

        bt6.setBackground(new java.awt.Color(102, 102, 102));
        bt6.setFont(new java.awt.Font("ROG Fonts", 3, 36)); // NOI18N
        bt6.setForeground(new java.awt.Color(255, 0, 0));
        bt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt6MouseClicked(evt);
            }
        });

        bt3.setBackground(new java.awt.Color(102, 102, 102));
        bt3.setFont(new java.awt.Font("ROG Fonts", 3, 36)); // NOI18N
        bt3.setForeground(new java.awt.Color(255, 0, 0));
        bt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt3MouseClicked(evt);
            }
        });

        bt9.setBackground(new java.awt.Color(102, 102, 102));
        bt9.setFont(new java.awt.Font("ROG Fonts", 3, 36)); // NOI18N
        bt9.setForeground(new java.awt.Color(255, 0, 0));
        bt9.setToolTipText("");
        bt9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt9MouseClicked(evt);
            }
        });

        bt7.setBackground(new java.awt.Color(102, 102, 102));
        bt7.setFont(new java.awt.Font("ROG Fonts", 3, 36)); // NOI18N
        bt7.setForeground(new java.awt.Color(255, 0, 0));
        bt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt7MouseClicked(evt);
            }
        });

        bt8.setBackground(new java.awt.Color(102, 102, 102));
        bt8.setFont(new java.awt.Font("ROG Fonts", 3, 36)); // NOI18N
        bt8.setForeground(new java.awt.Color(255, 0, 0));
        bt8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt8MouseClicked(evt);
            }
        });

        bt5.setBackground(new java.awt.Color(102, 102, 102));
        bt5.setFont(new java.awt.Font("ROG Fonts", 3, 36)); // NOI18N
        bt5.setForeground(new java.awt.Color(255, 0, 0));
        bt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout board_panelLayout = new javax.swing.GroupLayout(board_panel);
        board_panel.setLayout(board_panelLayout);
        board_panelLayout.setHorizontalGroup(
            board_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(board_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(board_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(board_panelLayout.createSequentialGroup()
                        .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(board_panelLayout.createSequentialGroup()
                        .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(board_panelLayout.createSequentialGroup()
                        .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(board_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        board_panelLayout.setVerticalGroup(
            board_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(board_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(board_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(board_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(board_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));

        ngbt.setBackground(new java.awt.Color(102, 102, 102));
        ngbt.setFont(new java.awt.Font("ROG Fonts", 2, 24)); // NOI18N
        ngbt.setForeground(new java.awt.Color(255, 0, 0));
        ngbt.setText("START Game");
        ngbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ngbt)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(board_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ngbt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188)))
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseClicked
bt1.setBackground(Color.black);
if(!"X".equals(bt1.getText()) && !"0".equals(bt1.getText()) )
if("X's turn!".equals(jLabel2.getText())) {       
bt1.setText("X");
jLabel2.setText("0's turn!");
}
else if("0's turn!".equals(jLabel2.getText())){ 
bt1.setText("0"); 
jLabel2.setText("X's turn!");}
else{
jLabel2.setText("OOPS! Something went wrong. Start New Game.");
}
check();
    }//GEN-LAST:event_bt1MouseClicked

    private void bt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt2MouseClicked
bt2.setBackground(Color.black);
if(!"X".equals(bt2.getText()) && !"0".equals(bt2.getText()) )        
if("X's turn!".equals(jLabel2.getText())) {       
bt2.setText("X");
jLabel2.setText("0's turn!");
}
else if("0's turn!".equals(jLabel2.getText())){ 
bt2.setText("0"); 
jLabel2.setText("X's turn!");}
else{
jLabel2.setText("OOPS! Something went wrong. Start New Game.");
}
check();
    }//GEN-LAST:event_bt2MouseClicked

    private void bt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt3MouseClicked
bt3.setBackground(Color.black);
if(!"X".equals(bt3.getText()) && !"0".equals(bt3.getText()) )       
if("X's turn!".equals(jLabel2.getText())) {       
bt3.setText("X");
jLabel2.setText("0's turn!");
}
else if("0's turn!".equals(jLabel2.getText())){ 
bt3.setText("0"); 
jLabel2.setText("X's turn!");}
else{
jLabel2.setText("OOPS! Something went wrong. Start New Game.");
}
check();
    }//GEN-LAST:event_bt3MouseClicked

    private void bt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt4MouseClicked
bt4.setBackground(Color.black);
if(!"X".equals(bt4.getText()) && !"0".equals(bt4.getText()) )     
if("X's turn!".equals(jLabel2.getText())) {       
bt4.setText("X");
jLabel2.setText("0's turn!");
}
else if("0's turn!".equals(jLabel2.getText())){ 
bt4.setText("0"); 
jLabel2.setText("X's turn!");}
else{
jLabel2.setText("OOPS! Something went wrong. Start New Game.");
}
check();
    }//GEN-LAST:event_bt4MouseClicked

    private void bt5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt5MouseClicked
bt5.setBackground(Color.black);
if(!"X".equals(bt5.getText()) && !"0".equals(bt5.getText()) )        
if("X's turn!".equals(jLabel2.getText())) {       
bt5.setText("X");
jLabel2.setText("0's turn!");
}
else if("0's turn!".equals(jLabel2.getText())){ 
bt5.setText("0"); 
jLabel2.setText("X's turn!");}
else{
jLabel2.setText("OOPS! Something went wrong. Start New Game.");
}
check();
    }//GEN-LAST:event_bt5MouseClicked

    private void bt6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt6MouseClicked
bt6.setBackground(Color.black);
if(!"X".equals(bt6.getText()) && !"0".equals(bt6.getText()) )       
if("X's turn!".equals(jLabel2.getText())) {       
bt6.setText("X");
jLabel2.setText("0's turn!");
}
else if("0's turn!".equals(jLabel2.getText())){ 
bt6.setText("0"); 
jLabel2.setText("X's turn!");}
else{
jLabel2.setText("OOPS! Something went wrong. Start New Game.");
}
check();
    }//GEN-LAST:event_bt6MouseClicked

    private void bt7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt7MouseClicked
bt7.setBackground(Color.black);
if(!"X".equals(bt7.getText()) && !"0".equals(bt7.getText()) )      
if("X's turn!".equals(jLabel2.getText())) {       
bt7.setText("X");
jLabel2.setText("0's turn!");
}
else if("0's turn!".equals(jLabel2.getText())){ 
bt7.setText("0"); 
jLabel2.setText("X's turn!");}
else{
jLabel2.setText("OOPS! Something went wrong. Start New Game.");
}
check();
    }//GEN-LAST:event_bt7MouseClicked

    private void bt8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt8MouseClicked
bt8.setBackground(Color.black);
if(!"X".equals(bt8.getText()) && !"0".equals(bt8.getText()) )       
if("X's turn!".equals(jLabel2.getText())) {       
bt8.setText("X");
jLabel2.setText("0's turn!");
}
else if("0's turn!".equals(jLabel2.getText())){ 
bt8.setText("0"); 
jLabel2.setText("X's turn!");}
else{
jLabel2.setText("OOPS! Something went wrong. Start New Game.");
}
check();
    }//GEN-LAST:event_bt8MouseClicked

    private void bt9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt9MouseClicked
bt9.setBackground(Color.black);
if(!"X".equals(bt9.getText()) && !"0".equals(bt9.getText()) )        
if("X's turn!".equals(jLabel2.getText())) {       
bt9.setText("X");
jLabel2.setText("0's turn!");
}
else if("0's turn!".equals(jLabel2.getText())){ 
bt9.setText("0"); 
jLabel2.setText("X's turn!");}
else{
jLabel2.setText("OOPS! Something went wrong. Start New Game.");
}
check();
    }//GEN-LAST:event_bt9MouseClicked

    private void ngbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngbtActionPerformed
ngbt.setText("NEW GAME");
bt1.setBackground(Color.red);
bt2.setBackground(Color.red);
bt3.setBackground(Color.red);
bt4.setBackground(Color.red);
bt5.setBackground(Color.red);
bt6.setBackground(Color.red);
bt7.setBackground(Color.red);
bt8.setBackground(Color.red);
bt9.setBackground(Color.red);
bt1.setText("1");
bt2.setText("2");
bt3.setText("3");
bt4.setText("4");
bt5.setText("5");
bt6.setText("6");
bt7.setText("7");
bt8.setText("8");
bt9.setText("9");        
jLabel2.setText("X's turn!");
    }//GEN-LAST:event_ngbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TTT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel board_panel;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ngbt;
    // End of variables declaration//GEN-END:variables
}
